collections:

  - name: settings
    label: Settings
    files:
      - name: general
        label: General
        file: content/settings/general.md
        fields:
          - label: Logo
            name: logo
            widget: image
